modules/simplesamlphp: read secrets from files
mayflower/nixexprs pull request #114
Opened 2020-09-08 12:02 UTC by WilliButz

2020-09-08 16:05 UTC, lheckemann submitted a review, later dismissed

2020-10-05 15:25 UTC, elseym requested changes

2020-10-05 15:25 UTC, elseym commented on modules/simplesamlphp.nix
> +
will not return `null` if file is empty. also probably more idiomatic:
```suggestion
    $adminpassword = trim(file_get_contents('${cfg.adminPasswordFile}'));
    $secretsalt = trim(file_get_contents('${cfg.secretSaltFile}'));

```

2020-10-07 11:13 UTC, elseym commented
closed in favour of #120

2020-10-07 11:13 UTC, closed without merging